[package]
name = "insert_dylib_rs"
version = "0.2.0"
authors = ["Cocoa <i@uwucocoa.moe>"]
edition = "2021"

[dependencies]
clap = "2"

[profile.release]
strip = true
opt-level = "z"
lto = true
panic = "abort"
